name: Uptime Check

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping health endpoint
        run: |
          if [ -z "${{ secrets.SITE_URL }}" ]; then
            echo "SITE_URL not set, skipping"
            exit 0
          fi
          curl -fsS ${{ secrets.SITE_URL }}/api/health || exit 1
